/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class DevinClientApiTimeoutError extends Error {
    constructor(message: string) {
        super(message);
        Object.setPrototypeOf(this, DevinClientApiTimeoutError.prototype);
    }
}
