/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevintestApi from "../../../index.js";

export interface Movie {
    id: DevintestApi.MovieId;
    title: string;
    /** The rating scale out of ten stars */
    rating: number;
}
